### ISSUE TITLE
PLEX v2 not trigering

### ISSUE THREAD

**Issue by crashtestoz** [iharosi/homebridge-plex-v2#1]
Hi, thank you for picking up the development of this plugin.

I can see the in the log that a client is playing but the plugin doe snot detect that ist playing. Also it doe snot detect the cleaned MediaLink from my old LG TV.

Any ideas?

<Mar  8 21:08:26 raspberrypi homebridge[571]: [2019-3-8 21:08:26] [Plex] →  [Xbox-SystemOS]: playing (ignored)
Mar  8 21:08:26 raspberrypi homebridge[571]: [2019-3-8 21:08:26] [Plex] Plex is not playing.
Mar  8 21:08:31 raspberrypi homebridge[571]: [2019-3-8 21:08:31] [Plex] Getting current state...
Mar  8 21:08:31 raspberrypi homebridge[571]: [2019-3-8 21:08:31] [Plex] There is one active session:
Mar  8 21:08:31 raspberrypi homebridge[571]: [2019-3-8 21:08:31] [Plex] →  [Xbox-SystemOS]: playing (ignored)
Mar  8 21:08:31 raspberrypi homebridge[571]: [2019-3-8 21:08:31] [Plex] Plex is not playing.>

**Comment by iharosi** [comment]
Hi @crashtestoz,
Can you share your `config.json`?
Don't forget to remove your `plex_token` before you share!

**Comment by crashtestoz** [comment]
Sure, here is the section with Plex

`"accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "my-token",
            "host": "10.0.0.20",
            "port": "32400",
            "polling_interval": "10",
            "filter": [
                {
                    "player": "Xbox-SystemOS"
                }
            ]
        },`

**Comment by iharosi** [comment]
Looks okay to me.

Normally you shouldn't see anything in the log besides the `[Plex] Plex is playing` message if you're not including `"debug": true` in your `config.json`.

Did it work before with the homebridge-plex plugin?
Don't forget to uninstall the homebridge-plex plugin:  
`npm uninstall -g homebridge-plex` and then `npm i -g homebridge-plex-v2`.
Make sure you need to use these commands with `sudo`.
Try to remove the `accessories` and `persist` folder and with that re-register homebridge with your HomeKit system after you replaced the plugins.

**Comment by crashtestoz** [comment]
I only used the homebridge-plex-v2. I think the plugin is working now when I use the xbox player of the apple-tv.

My only problem is that the LG TV MediaLink client for Plex does not show up in the Plex Sever and as such the homebridge plugin doe snot pick it up. MediaLink is no longer supported by Plex so that is probably why.

**Comment by iharosi** [comment]
Have you put MediaLink client into the filter in your config file?

**Comment by crashtestoz** [comment]
Yes, MediaLink does not have the ability to user a user/pass for authentication. My LAN is filtered so that no client needs to login. However even so, Apple-TV shows up and all other clients except MediaLink. I am going to update PLEX to the latest version and see. I think its just MediaLink being odd.

**Comment by iharosi** [comment]
@crashtestoz Unfortunately, I'm not able to test with MediaLink but if this happens because of the lack of support from LG side I don't think we can do much.
I'm going to close this issue for now but please let me know if you have any update!

**Comment by MCGregorUK** [comment]
I had the same issue with a LG-TV
To bad, but i had to disable the plugin 😔

I would be happy if it could be fixed...

**Comment by iharosi** [comment]
Unfortunately LG has dropped MediaLink support, there's not much we can do. You should get a media box which supports Plex client (i.e. AppleTV) or upgrade your TV to a newer model running WebOS. :-/
