### ISSUE TITLE
Request: More filter objects

### ISSUE THREAD

**Issue by MikeDeltaHH** [iharosi/homebridge-plex-v2#10]
Hi!

Is it possible to integrate more filter objects like media categories (movie, show, episode, etc.)?

Regards!
Mike

**Comment by iharosi** [comment]
Hi @MikeDeltaHH,

In case you have a plex pass you can use [homebridge-plex-webhooks](https://github.com/iharosi/homebridge-plex-webhooks), with that you can create more filters. You can find examples here: https://support.plex.tv/articles/115002267687-webhooks/#toc-3

Regarding this plugin, I need to investigate if it's possible at all.
Please note, **homebridge-plex-v2** development is not my primary focus anymore so, I can't promise anything in a realistic time.

**Comment by MikeDeltaHH** [comment]
Hi @iharosi,
Thanks for your answer - the webhhoks don't work for me since a few days, i searched for the cause for hours without success and therefore i switched to your plugin. If you can install it someday, fine, but the plugin also works very well!

**Comment by adjoseph16** [comment]
Just chiming in that I would absolutely love more filter options if possible.

**Comment by iharosi** [comment]
Hey guys, I doesn't really maintaining this project anymore. Please check out this one instead: https://github.com/iharosi/homebridge-plex-webhooks
It requires Plex Pass however it works much more reliably and faster.
Also, you can take a look at the original [homebridge-plex](https://github.com/mpbzh/homebridge-plex) plugin if you don't have Plex Pass.
Cheers
