### ISSUE TITLE
[Plex] Error: connect ECONNREFUSED 127.0.0.1:32400

### ISSUE THREAD

**Issue by OLTSYS** [iharosi/homebridge-plex-v2#2]
Hello,

Recently, I got an error when launching the PLEX v2 plugin for Homebridge :

[Plex] Error: connect ECONNREFUSED 127.0.0.1:32400

Do you have an idea about this issue ? 
It seems that "localhost" is waited instead of "127.0.0.1" but where can I change this ?

Thank you

**Comment by iharosi** [comment]
Hi,

Check the README.md of this page (https://github.com/iharosi/homebridge-plex-v2).
You can see the config options there. You can use `host` and `port` keys to change the defaults in your `config.json`.

Hope it helps!

**Comment by OLTSYS** [comment]
It helps ! Everything is running properly now :)

Many thanks !
