### ISSUE TITLE
[Plex] Error: socket hang up

### ISSUE THREAD

**Issue by leconnaisseur** [iharosi/homebridge-plex-v2#5]
Hey iharosi!
I have trouble getting the plugin to run.
Token is set, host, port, user and player as well. So is a webhook directing towards the IP of my homebridge.
The plugin still fails with [Plex] Error: socket hang up. Do you have any idea what might be the cause? Here's my config:
```
  "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "host": "192.168.2.82",
            "port": "32400",
            "plex_token": "xxxxxxxxx",
            "filter": [
                {
                    "user": "xxxxx",
                    "player": "LG yyyyyy"
                }
            ]
        }
    ],
```
I really hope you have an idea for me! Thanks for all the work on this fork!

**Comment by iharosi** [comment]
Hi,
Are you able to reach the Plex Web UI with the given host and port (http://192.168.2.82:324000) in a browser from that machine where you have homebridge set up?
