### ISSUE TITLE
Multiple Plex sensors?

### ISSUE THREAD

**Issue by coderandgentleman** [iharosi/homebridge-plex-v2#8]
Is there a way to have multiple sensors? One for each Plex source? Thanks!

**Comment by iharosi** [comment]
I haven't tried but it should work if you add another accessory to your homebridge, like this:
```
{
  "accessories": [
    {
      "accessory": "Plex",
      "name": "Plex",
      "plex_token": "...",
      "filter": [
        {
            "user": "your-plex-username",
            "player": "your-favorite-player"
        }
      ]
    },
    {
      "accessory": "Plex",
      "name": "2nd Plex",
      "plex_token": "...",
      "filter": [
        {
            "user": "your-2nd-plex-username",
            "player": "your-2nd-favorite-player"
        }
      ]
    }
  ]
}
```
Just make sure the `accessory` is always "Plex" and the `name` is always different.
Please let me know about your experience it will help other people to create similar setups!
Thanks!
