### ISSUE TITLE
error in work

### ISSUE THREAD

**Issue by motogon** [iharosi/homebridge-plex-v2#9]
Hi 

homebridge[8964]: [2020-6-13 6:15:18 PM] [Plex] Cannot read property 'forEach' of undefined

**Comment by motogon** [comment]
my config:

 {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "xxxxxxxxx",
            "host": "192.168.1.108",
            "filter": [
                {
                    "user": "xxxx",
                    "player": "xxxxxx"
                }
            ]
        }

**Comment by iharosi** [comment]
Sorry guys, but I'm not planning to continue maintaining this project anymore. Please check out this one instead: https://github.com/iharosi/homebridge-plex-webhooks
It requires Plex Pass however it works much more reliably and faster.
Also, you can take a look at the original [homebridge-plex](https://github.com/mpbzh/homebridge-plex) plugin if you don't have Plex Pass.
Cheers
